### ISSUE TITLE
Prevent event propagation

### ISSUE THREAD

**Issue by pbiggar** [Gizra/elm-keyboard-event#2]
This is a great library, and thanks for making it. I'm using the `onWindow` version, and the extra modifier keys in the decoder are great. However, I'm also looking to use stopPropagation and preventDefault, as is done in `Html.Events.onWithOptions`. Do you have a suggestion for how I could include this?

Thanks!

**Comment by rgrempel** [comment]
Hmm. I don't think it's possible ... the `onWindow` function doesn't provide a mechanism for calling `preventDefault` or `stopPropagation` on the event. It's a limitation of the `elm-lang/dom` package that gives us `onWindow`.

**Comment by pbiggar** [comment]
Thanks! I ended up catching these outside of the elm app.
