### ISSUE TITLE
Make considerKeyboardEvent elm-spec compatible

### ISSUE THREAD

**Issue by jamespeterschinner** [Gizra/elm-keyboard-event#5]
Hi, 

I've been using `considerKeyboardEvent` with success however I have run into an issue when I try and use [elm-spec](https://package.elm-lang.org/packages/brian-watkins/elm-spec/latest/#:~:text=elm%2Dspec%20allows%20you%20to,you%20can%20if%20you%20wish). The issue is that elm-spec doesn't generate events containing all the fields required for a `KeyboardEvent`.

I modified a local version making the following changes to the `decodeKeyboardEvent` which solved the issue, all it does is apply default values `False` to any missing fields upon construction. Is this a non-breaking change to the API? and could it be included in a new version or an addition to the library?

```
defaultFalse: Decoder Bool ->  Decoder Bool
defaultFalse decoderBool  =
    map (Maybe.withDefault <| False) <| (maybe decoderBool)

decodeKeyboardEvent : Decoder KeyboardEvent
decodeKeyboardEvent =
    map7 KeyboardEvent
        (defaultFalse (field "altKey" bool))
        (defaultFalse (field "ctrlKey" bool))
        decodeKey
        (map fromCode decodeKeyCode)
        (defaultFalse (field "metaKey" bool))
        (defaultFalse (field "repeat" bool))
        (defaultFalse (field "shiftKey" bool))
```
**UPDATE**

Ok nevermind with this one, turns out I can generate any event I like with elm-spec! I was Just my usage. Cheers

**Comment by amitaibu** [comment]
For context, here's the answer on how to use with elm-spec -- https://discourse.elm-lang.org/t/triggering-arrowup-in-elm-spc/6457/4?u=amitaibu
