### ISSUE TITLE
Mention dependency on proper-keyboard?

### ISSUE THREAD

**Issue by schoettl** [Gizra/elm-keyboard-event#6]
Hi, thanks for this great package!

Though, it took me a while to figure out that it depends on SwiftsNamesake/proper-keyboard which is needed to use the `keyCode : Key` field.  I first looked into your code and found `import Keyboard.Key` but then I still didn't know from which package it comes. Later I found it in the dependency definition.

But for beginners, it would be helpful to mention it in the README and maybe explicitly import `Key` from `Keyboard.Key`. Would you accept a PR for this?

**Comment by amitaibu** [comment]
> Would you accept a PR for this?

:+1:
